### ISSUE TITLE
gmapping crashes when using sweep

### ISSUE THREAD

**Issue by sevenbitbyte** [scanse/sweep-ros#14]
[Gmapping](http://wiki.ros.org/gmapping) does not work out of the box with the sweep. I setup a pipeline of sweep -> pointcloud_to_laserscan -> gmapping. Gmapping crashes as soon as the first scan comes in.

**Comment by vitorboschi** [comment]
I had this issue and it turned out that pointcloud_to_laserscan was generating a really dense scan by default. Gmapping couldn't get enough memory to process it and crashed. The solution I've found was to set a smaller value for angle_increment in pointcloud_to_laserscan, like 0.0174533 (1 degree).

**Comment by sevenbitbyte** [comment]
Oh great point, this seems to have been my issue. Clearly not a bug in sweep so closing this issue.

**Comment by yubenjamin2** [comment]
Hi @sevenbitbyte do you remember what the crash was? Having a similar issue but was wondering if your gmapping crashing is similar to my scenario. (Tried the solution proposed by @vitorboschi  but it didn't work. 

Basically after it says "Registering first scan" the gmapping process just dies before it can even create the associated log file, which isn't helpful. 

Thanks
