### ISSUE TITLE
Command Byte Issues with 16.04

### ISSUE THREAD

**Issue by ltecot** [scanse/sweep-ros#5]
The ROS node does not work for 16.04 and responds with the following errors when run. 
Inside the "while(ros::ok())" loop, getCompleteScan first returns with S_TIMEOUT, then hangs on the second call.  This can be tracked back to scan_ready never being signaled in _pollScanData, which can in turn be traced back to a call in startScan. I observed that startScan fails on the response header check. response_header.cmdByte1 and response_header.cmdByte2 are set to 0 and 1 respectively, which is not equal to the constants given in the following if statement. I did not look any deeper into what these bytes are, nor why I was getting the errors below.
The visualizer also worked fine for me, the only issue is with the ROS node.

```
roslaunch sweep_ros sweep.launch 
... logging to /home/lucas/.ros/log/17e6dc70-1a2a-11e7-bd77-001c428f4b12/roslaunch-ubuntu-7860.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:46363/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /sweep_node/frame_id: laser_frame
 * /sweep_node/rotation_speed: 5
 * /sweep_node/serial_baudrate: 115200
 * /sweep_node/serial_port: /dev/ttyUSB0

NODES
  /
    sweep_node (sweep_ros/sweep_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[sweep_node-1]: started with pid [7881]
[ERROR] [1491419263.649069006]: Error, couldn't set rotation speed
[ERROR] [1491419263.654514855]: Error, couldn't retrieve device info
[ERROR] [1491419263.660010292]: Error, couldn't retrieve device info
[ERROR] [1491419263.660212565]: Error, unknown Sweep Model
[ERROR] [1491419263.660305504]: Error, coudln't verify device info
```

**Comment by ltecot** [comment]
I am also having his issue with 14.04.

**Comment by kent-williams** [comment]
Hi @Cranapple, sorry to hear you're having trouble!

We are a few days away from updating the ROS driver with our new SDK. If you can wait a little, it will be a much more robust solution!

In the meantime though it does sound like this might have something to do with your setup rather than a bug, since several people are using it successfully on 14.04 and 16.04.  For starters, is anything else possibly opening that serial port and contributing to some corruption while you're attempting to use the ros node?

**Comment by ltecot** [comment]
Thank you for the reply! And yes you were right, I didn't pinpoint down exactly what went wrong but after fiddling with the node setup for a while it started to work.
