### ISSUE TITLE
Timeout at getCompleteScan 

### ISSUE THREAD

**Issue by syd-blue** [scanse/sweep-ros#6]
Hi 
I received two of the Sweep's few hours ago. They are working perfect with the Sweep Visualizer tool, but they are not working with your ROS node. I digged into it a little bit and noticed that the getCompleteScan method returns a timeout every time. Do you know anything about that? 

Thanks

**Comment by dcyoung** [comment]
Hi there syd-blue,
At this time the sweep-ros driver is only compatible with sweep firmware v1.0. I have updated the [README ](https://github.com/scanse/sweep-ros) to reflect this.

Once an update is released to support later firmware, please let us know if you are still experiencing the issue.

**Comment by syd-blue** [comment]
Hi dcyoung

Thank you for the fast reply. I'm looking forward for your update.  For the beginning I adapted your node to the new sweep_sdk. So it's working for now. 
Although I recognized that sometimes the driver is hanging up. But this will be an issue for the sweep_sdk I think. 

Best regards 
Sydney

**Comment by kent-williams** [comment]
Hi @syd-blue 

The ROS driver has now been updated to the new sdk.

-Kent
